import { expect, test, type Page } from '@playwright/test'
import { openSpecs, openViewer } from './support'

async function selectObject(page: Page, name: string, showSpecs = true): Promise<void> {
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  await page.getByLabel('Search objects').fill(name)
  await page.getByRole('button', { name: `Select ${name}`, exact: true }).click()
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  if (showSpecs) await openSpecs(page)
}

test('loads Centaurus on demand and follows exact components across locked charts', { tag: '@mobile' }, async ({ page }, testInfo) => {
  const chartRequests: string[] = []
  page.on('request', (request) => {
    if (/\/(canis-major|centaurus)-[^/]+\.js(?:\?|$)/.test(request.url())) chartRequests.push(request.url())
  })
  await openViewer(page)
  expect(chartRequests).toHaveLength(0)
  await selectObject(page, 'Alpha Centauri A')
  await page.locator('#constellation-toggle').click()
  const card = page.locator('#constellation-card')
  await expect(card.locator('#constellation-heading')).toHaveText('Constellation: Centaurus')
  await expect(card.locator('.constellation-star')).toHaveCount(17)
  await expect(card.locator('.constellation-bayer')).toHaveCount(15)
  await expect(card.locator('.constellation-line')).toHaveCount(16)
  await expect(card.locator('.constellation-boundary')).toHaveCount(20)
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Alpha Centauri A')
  expect((await card.locator('.constellation-neighbor').allTextContents()).sort())
    .toEqual(['Antlia', 'Carina', 'Circinus', 'Crux', 'Hydra', 'Lupus', 'Musca', 'Vela'])
  expect(chartRequests.filter((url) => url.includes('/centaurus-'))).toHaveLength(1)
  expect(chartRequests.some((url) => url.includes('/canis-major-'))).toBe(false)
  const layout = await card.locator('#constellation-chart > svg').evaluate((diagram) => {
    const bounds = diagram.getBoundingClientRect()
    const labels = [...diagram.querySelectorAll('.constellation-star-name, .constellation-bayer, .constellation-neighbor')]
      .map((label) => label.getBoundingClientRect())
    return {
      fits: labels.every((label) => label.left >= bounds.left && label.right <= bounds.right && label.top >= bounds.top && label.bottom <= bounds.bottom),
      overlaps: labels.some((a, i) => labels.slice(i + 1).some((b) => a.left < b.right && a.right > b.left && a.top < b.bottom && a.bottom > b.top)),
    }
  })
  expect(layout).toEqual({ fits: true, overlaps: false })
  await card.screenshot({ path: testInfo.outputPath('centaurus-card.png') })
  await page.locator('#constellation-lock').click()
  await page.getByRole('button', { name: 'Show Alpha Centauri B', exact: true }).click()
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Alpha Centauri B')
  await expect(card.locator('[data-hip="71683"] .constellation-star-name')).toHaveCount(0)
  await page.getByRole('button', { name: 'Show Alpha Centauri C (Proxima Centauri)', exact: true }).click()
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Proxima Centauri')
  await expect(card.locator('[data-hip="71683"] .constellation-bayer')).toHaveText('α')
  const beta = card.locator('[data-hip="68702"]')
  const betaName = (await beta.getAttribute('aria-label'))!.replace(/^Select /, '')
  await beta.click()
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText(betaName)
  await expect(page.locator('#inspector')).toHaveAttribute('data-selected-star', 'bright-hadar')
  await expect(card.locator('#constellation-visibility')).toBeVisible()
  await selectObject(page, 'Sirius A', false)
  await expect(card.locator('#constellation-heading')).toHaveText('Constellation: Canis Major')
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Sirius A')
  await selectObject(page, 'Alpha Centauri A', false)
  await expect(card.locator('#constellation-heading')).toHaveText('Constellation: Centaurus')
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Alpha Centauri A')
  expect(chartRequests.filter((url) => url.includes('/centaurus-'))).toHaveLength(1)
})

test('maps visible latitudes and updates the evening month bar for the selected latitude', { tag: '@mobile' }, async ({ page }, testInfo) => {
  await openViewer(page)
  await openSpecs(page)
  await page.locator('#constellation-toggle').click()
  const card = page.locator('#constellation-card')
  const visibility = card.locator('#constellation-visibility')
  await expect(visibility).toBeVisible()
  await expect(card.locator('#constellation-visible-latitudes-value')).toHaveText('90° S–73.3° N')
  await expect(card.locator('#constellation-visible-months-value')).toHaveText('Dec–Apr')
  await expect(card.locator('.constellation-map-latitude')).toHaveCount(9)
  await expect(card.locator('.constellation-visibility-month')).toHaveCount(12)
  expect(await card.locator('.constellation-visibility-month.is-visible').evaluateAll((months) => months.map((month) => (month as HTMLElement).dataset.month))).toEqual(['Jan', 'Feb', 'Mar', 'Apr', 'Dec'])
  await expect.poll(() => card.locator('.constellation-map-visible-land').evaluate((land) => getComputedStyle(land).fill)).toBe('rgb(0, 0, 0)')
  const layout = await visibility.evaluate((section) => {
    const map = section.querySelector('#constellation-visibility-map')!.getBoundingClientRect()
    const bar = section.querySelector('#constellation-visibility-months')!.getBoundingClientRect()
    const tracks = [...section.querySelectorAll('.constellation-visibility-month i')].map((track) => track.getBoundingClientRect().height)
    return { mapLeft: map.left, mapRight: map.right, barLeft: bar.left, fits: section.scrollWidth <= section.clientWidth, tracks }
  })
  expect(layout.barLeft).toBeGreaterThan(layout.mapRight)
  expect(layout.fits).toBe(true)
  expect(layout.tracks.every((height) => height === 16)).toBe(true)
  await card.screenshot({ path: testInfo.outputPath('constellation-visibility.png') })
  await page.getByLabel('Latitude', { exact: true }).selectOption('80')
  await expect(card.locator('#constellation-visible-months-value')).toHaveText('None at 10 pm')
  await expect(card.locator('.constellation-visibility-month.is-visible')).toHaveCount(0)
  await page.getByLabel('Latitude', { exact: true }).selectOption('0')
  await expect(card.locator('#constellation-visible-months-value')).toHaveText('Nov–Apr')
  await card.getByRole('button', { name: 'Select Adhara', exact: true }).click()
  await expect(page.getByLabel('Latitude', { exact: true })).toHaveValue('0')
  await expect(card.locator('#constellation-visible-latitudes-value')).toHaveText('90° S–61.0° N')
  await expect(card.locator('#constellation-visibility-months')).toHaveAttribute('aria-label', /^Adhara at 0°/)
})

test('shows a labelled Canis Major chart with orange selection, lock, and close controls', { tag: '@mobile' }, async ({ page }, testInfo) => {
  await openViewer(page)
  await openSpecs(page)
  await page.locator('#constellation-row dt').click()
  const card = page.locator('#constellation-card')
  await expect(card).toBeVisible()
  await expect(page.locator('#constellation-heading')).toHaveText('Constellation: Canis Major')
  await expect(card.locator('#constellation-chart title')).toHaveCount(0)
  await expect(card.locator('.constellation-star-name')).toHaveCount(1)
  await expect(card.locator('.constellation-bayer')).toHaveCount(15)
  await expect(card.locator('.constellation-selected-ring')).toHaveCount(1)
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Sirius A')
  await expect.poll(() => card.locator('.is-selected .constellation-star-name').evaluate((label) => getComputedStyle(label).fill)).toBe('rgb(255, 138, 42)')
  await expect(card.locator('[data-hip="33579"] .constellation-bayer')).toHaveText('ε')
  const labels = await card.locator('.constellation-star-name, .constellation-bayer').evaluateAll((labels) => labels.map((label) => {
    const bounds = label.getBoundingClientRect(), chart = label.closest('svg')!.getBoundingClientRect()
    return { fits: bounds.left >= chart.left && bounds.right <= chart.right && bounds.top >= chart.top && bounds.bottom <= chart.bottom,
      selected: label.parentElement!.classList.contains('is-selected'), fontSize: getComputedStyle(label).fontSize }
  }))
  expect(labels.every((label) => label.fits)).toBe(true)
  expect(labels.every((label) => label.fontSize === (label.selected ? '14px' : '12px'))).toBe(true)
  const labelBounds = await card.locator('.constellation-star-name, .constellation-bayer').evaluateAll((labels) => labels.map((label) => {
    const box = label.getBoundingClientRect()
    return { left: box.left, top: box.top, right: box.right, bottom: box.bottom }
  }))
  for (let first = 0; first < labelBounds.length; first++) {
    for (let second = first + 1; second < labelBounds.length; second++) {
      const a = labelBounds[first]!, b = labelBounds[second]!
      expect(a.right <= b.left || b.right <= a.left || a.bottom <= b.top || b.bottom <= a.top).toBe(true)
    }
  }
  await expect(card.locator('.constellation-boundary')).toHaveCount(6)
  expect((await card.locator('.constellation-neighbor').allTextContents()).sort()).toEqual(['Columba', 'Lepus', 'Monoceros', 'Puppis'])
  const framing = await card.locator('#constellation-chart > svg').evaluate((diagram) => {
    const chart = diagram.getBoundingClientRect()
    const ys = [...diagram.querySelectorAll<SVGGElement>('.constellation-star')].map((star) => Number(star.dataset.y))
    const viewHeight = (diagram as SVGSVGElement).viewBox.baseVal.height
    const neighbors = [...diagram.querySelectorAll('.constellation-neighbor')].map((label) => label.getBoundingClientRect())
    const borders = [...diagram.querySelectorAll('.constellation-boundary')].map((border) => border.getBoundingClientRect())
    return { figureFraction: (Math.max(...ys) - Math.min(...ys)) / viewHeight,
      bordersVisible: borders.every((border) => border.left >= chart.left && border.right <= chart.right && border.top >= chart.top && border.bottom <= chart.bottom),
      neighborsAtCorners: neighbors.every((label) => (label.left < chart.left + chart.width / 4 || label.right > chart.right - chart.width / 4)
        && (label.top < chart.top + chart.height / 8 || label.bottom > chart.bottom - chart.height / 8)) }
  })
  expect(framing.figureFraction).toBeGreaterThan(0.7)
  expect(framing.bordersVisible).toBe(true)
  expect(framing.neighborsAtCorners).toBe(true)
  await expect(card.locator('[data-hip="32349"] .constellation-bayer')).toHaveText('α')
  await expect.poll(() => card.locator('.constellation-sources').evaluate((section) => getComputedStyle(section).borderTopStyle)).toBe('solid')
  await card.screenshot({ path: testInfo.outputPath('canis-major.png') })
  await page.getByRole('button', { name: 'Keep Constellation open', exact: true }).click()
  const viewport = page.viewportSize()!
  await page.mouse.move(viewport.width / 2, viewport.height - 110)
  await page.mouse.down()
  await page.mouse.move(viewport.width / 2 + 20, viewport.height - 100, { steps: 3 })
  await page.mouse.up()
  await expect(card).toBeVisible()
  await expect(page.locator('#constellation-lock')).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Close constellation card', exact: true }).click()
  await expect(card).toBeHidden()
  await expect(page.locator('#constellation-toggle')).toBeFocused()
  await page.locator('#constellation-toggle').press('Enter')
  await expect(card).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(card).toBeHidden()
  await expect(page.locator('#constellation-toggle')).toBeFocused()
  await page.locator('#constellation-toggle').click()
  await page.locator('#constellation-lock').click()
  await page.mouse.move(viewport.width / 2, viewport.height - 110)
  await page.mouse.down()
  await page.mouse.move(viewport.width / 2 + 20, viewport.height - 100, { steps: 3 })
  await page.mouse.up()
  await expect(card).toBeHidden()
})

test('keeps Sirius B separate from the figure star and disables unreviewed charts', async ({ page }, testInfo) => {
  await openViewer(page)
  await openSpecs(page)
  await page.locator('#constellation-toggle').click()
  await page.locator('#constellation-lock').click()
  await page.getByRole('button', { name: 'Show Sirius B', exact: true }).click()
  const card = page.locator('#constellation-card')
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Sirius B')
  await expect(card.locator('.constellation-star-name')).toHaveCount(1)
  await expect(card.locator('[data-hip="32349"] .constellation-star-name')).toHaveCount(0)
  await expect(card.locator('[data-hip="32349"] .constellation-bayer')).toHaveText('α')
  await card.screenshot({ path: testInfo.outputPath('canis-major-sirius-b.png') })
  await card.getByText('Sources', { exact: true }).click()
  await expect(page.locator('#constellation-source-links a')).toHaveCount(4)
  await selectObject(page, 'Ross 154')
  await expect(card).toBeHidden()
  await expect(page.locator('#constellation-toggle')).toBeDisabled()
})

test('selects figure stars with tooltips while the constellation overlay is off', { tag: '@mobile' }, async ({ page }, testInfo) => {
  await openViewer(page)
  await openSpecs(page)
  await page.locator('#constellation-toggle').click()
  const card = page.locator('#constellation-card')
  const mirzam = card.getByRole('button', { name: 'Select Mirzam', exact: true })
  await mirzam.focus()
  const tooltip = page.locator('#constellation-tooltip-30324')
  await expect(tooltip).toBeVisible()
  await expect(tooltip.locator('.constellation-tooltip-object')).toHaveText('Mirzam')
  await expect(tooltip.locator('.star-swatch')).toBeVisible()
  await expect(tooltip.locator('.constellation-tooltip-metric > span')).toHaveText(['Distance from Sun', 'Apparent magnitude'])
  await expect(tooltip.locator('.constellation-tooltip-metric strong').nth(0)).toHaveText(/^[\d,]+ ly$/)
  await expect(tooltip.locator('.constellation-tooltip-metric strong').nth(1)).toHaveText('2.0')
  const box = await tooltip.boundingBox(), chartBox = await page.locator('#constellation-chart').boundingBox()
  expect(box!.x).toBeGreaterThanOrEqual(chartBox!.x)
  expect(box!.x + box!.width).toBeLessThanOrEqual(chartBox!.x + chartBox!.width)
  const rows = await tooltip.locator(':scope > span').evaluateAll((rows) => rows.map((row) => {
    const box = row.getBoundingClientRect(), parent = row.parentElement!.getBoundingClientRect()
    return { top: box.top, bottom: box.bottom, parentTop: parent.top, parentBottom: parent.bottom }
  }))
  expect(rows.every((row) => row.top >= row.parentTop && row.bottom <= row.parentBottom)).toBe(true)
  await card.screenshot({ path: testInfo.outputPath('mirzam-tooltip.png') })
  await mirzam.press('Enter')
  await expect(page.locator('#star-name')).toHaveText('Mirzam')
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Mirzam')
  await expect(card.locator('.constellation-star-name')).toHaveCount(1)
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: 'Select Adhara', exact: true }).click()
  await expect(page.locator('#star-name')).toHaveText('Adhara')
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('Adhara')
  await expect(page.locator('#show-western-constellation-stars')).not.toBeChecked()
})

test('plots a non-star at its own sky coordinates in Canis Major', async ({ page }, testInfo) => {
  await openViewer(page)
  await page.getByRole('button', { name: 'Filter', exact: true }).click()
  await page.getByRole('switch', { name: 'Stellar remnants', exact: true }).check()
  await page.locator('details.filter-dropdown > summary').click()
  await page.getByLabel('Pulsars', { exact: true }).check()
  await page.locator('#object-distance-limit').fill('24')
  await selectObject(page, 'PSR J0630-2834')
  await page.locator('#constellation-toggle').click()
  const card = page.locator('#constellation-card')
  await expect(card.locator('.is-selected')).toHaveAttribute('data-object-type', 'pulsar')
  await expect(card.locator('.is-selected .constellation-star-name')).toHaveText('PSR J0630-2834')
  await expect(card.locator('.constellation-selected-ring')).toHaveCount(1)
  await expect(card.locator('.constellation-star-name')).toHaveCount(1)
  await card.screenshot({ path: testInfo.outputPath('canis-major-pulsar.png') })
})
