import { expect, test } from '@playwright/test'

for (const planet of [
  { id: 'uranus', temperature: '76 K', moons: ['Miranda', 'Ariel', 'Umbriel', 'Titania', 'Oberon'], imageWidth: 1720 },
  { id: 'neptune', temperature: '72 K', moons: ['Proteus', 'Triton', 'Nereid'], imageWidth: 2188 },
]) {
  test(`${planet.id} card supports globe comparison, Info and only major moons`, { tag: '@mobile' }, async ({ page }, testInfo) => {
    const errors: string[] = []
    page.on('pageerror', (error) => errors.push(error.message))
    page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()) })
    await page.goto('/')
    await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
    await page.evaluate(() => document.fonts.ready)
    const objects = page.getByRole('button', { name: 'Objects', exact: true })
    if (await objects.getAttribute('aria-expanded') === 'false') await objects.click()
    await page.getByLabel('Search objects').fill('Sun')
    await page.getByRole('button', { name: 'Select Sun', exact: true }).click()
    await page.locator('#object-system-toggle').click()
    // Moving from Saturn must clear its rings and use the selected globe.
    await page.locator('.planet-row[data-planet-id="saturn"] button').click()
    await expect(page.locator('#planet-globe')).toHaveAttribute('data-rings-ready', 'true')
    await page.keyboard.press('Escape')
    await page.locator(`.planet-row[data-planet-id="${planet.id}"] button`).click()
    const card = page.locator('#planet-card')
    const canvas = page.locator('#planet-globe')
    await expect(canvas).toHaveAttribute('data-planet-id', planet.id)
    await expect(canvas).toHaveAttribute('data-texture-ready', 'true')
    await expect(canvas).toHaveAttribute('data-rings-visible', 'false')
    await expect(card.getByRole('button', { name: 'Orbit', exact: true })).toHaveCount(0)
    await expect(card.locator('[data-planet-spec="surface-temperature"]')).toContainText(planet.temperature)
    await expect(card.locator('[data-planet-spec="surface-pressure"]')).toContainText('No solid surface')
    await expect(card).not.toContainText(/NaN|undefined/)
    await canvas.focus()
    await page.keyboard.press('ArrowRight')
    await page.locator('#planet-add-earth').click()
    await expect(canvas).toHaveAttribute('data-earth-texture-ready', 'true')
    await expect(canvas).toHaveAttribute('aria-label', /same diameter scale/)
    const pinnedBounds = await canvas.boundingBox()
    await card.locator('.card-scroll-content').evaluate((element) => { element.scrollTop = 400 })
    expect(await canvas.boundingBox()).toEqual(pinnedBounds)
    await card.locator('.card-scroll-content').evaluate((element) => { element.scrollTop = 0 })
    await card.screenshot({ path: testInfo.outputPath(`${planet.id}-earth.png`) })
    await page.locator('#planet-info-toggle').click()
    await expect(page.locator('#planet-info > section')).toHaveCount(6)
    await expect(page.locator('#planet-info img')).toHaveJSProperty('naturalWidth', planet.imageWidth)
    await expect(page.locator('#planet-info')).toContainText('Voyager 2')
    await card.screenshot({ path: testInfo.outputPath(`${planet.id}-info.png`) })
    await page.locator('#planet-moons-toggle').click()
    await expect(page.locator('#planet-moons h3')).toHaveText(planet.moons)
    if (planet.id === 'neptune') await expect(page.locator('[data-planet-spec="moon-triton-sidereal-orbit"]')).toContainText('retrograde')
    await expect(card).not.toContainText(/NaN|undefined/)
    await card.screenshot({ path: testInfo.outputPath(`${planet.id}-moons.png`) })
    // A zero-moon planet must reset the tab, comparison and moon content.
    await page.keyboard.press('Escape')
    await page.locator('.planet-row[data-planet-id="venus"] button').click()
    await expect(canvas).toHaveAttribute('data-planet-id', 'venus')
    await expect(canvas).toHaveAttribute('data-texture-ready', 'true')
    await expect(canvas).toHaveAttribute('data-comparing-earth', 'false')
    await expect(page.locator('#planet-specs')).toBeVisible()
    await expect(page.locator('#planet-moons-toggle')).toBeHidden()
    await expect(page.locator('#planet-moons > section')).toHaveCount(0)
    expect(errors).toEqual([])
  })
}
