import { expect, test } from '@playwright/test'
import { selectCatalog } from './support'

test('shows resolved Achird iron abundances and distinguishes Gaia overall metallicity', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await selectCatalog(page, 'nearest-1000')
  const objects = page.getByRole('button', { name: 'Objects', exact: true })
  await objects.click()
  await page.getByLabel('Search objects').fill('Achird')
  await page.getByRole('button', { name: 'Select Achird', exact: true }).click()
  await page.locator('[data-component-id="cns5-0239"]').click()
  await expect(page.locator('[data-component-id="cns5-0239"]')).toHaveAttribute('aria-pressed', 'true')
  await page.locator('#object-specs-toggle').click()
  await expect(page.locator('#metallicity-label')).toHaveText('Metallicity [Fe/H]')
  await expect(page.locator('#metallicity')).toHaveText('-0.23 dex')
  await page.locator('#metallicity-toggle').click()
  await expect(page.locator('#metallicity-heading')).toHaveText('Metallicity [Fe/H]')
  await expect(page.locator('#metallicity-description')).toContainText('iron relative to hydrogen')
  await expect(page.locator('#metallicity-scale')).toHaveAttribute('aria-label', /iron-to-hydrogen/)
  await page.locator('[data-component-id="cns5-0238"]').click()
  await expect(page.locator('#metallicity-label')).toHaveText('Metallicity [Fe/H]')
  await expect(page.locator('#metallicity')).toHaveText('-0.305 dex')
  await expect(page.locator('#temperature')).toContainText('4,011')
  await expect(page.locator('#mass')).toContainText('0.549')
  await expect(page.locator('#radius')).toContainText('0.57')
  await page.locator('#metallicity-close').click()
  if (await objects.getAttribute('aria-expanded') !== 'true') await objects.click()
  await page.getByLabel('Search objects').fill('Proxima')
  await page.getByRole('button', { name: 'Select Proxima Centauri', exact: true }).click()
  await expect(page.locator('#metallicity-label')).toHaveText('Metallicity [M/H]')
  await page.locator('#metallicity-toggle').click()
  await expect(page.locator('#metallicity-heading')).toHaveText('Metallicity [M/H]')
  await expect(page.locator('#metallicity-description')).toContainText('metals relative to hydrogen')
  await expect(page.locator('#metallicity-scale')).toHaveAttribute('aria-label', /metal-to-hydrogen/)
})
