import { expect, test, type Page } from '@playwright/test'
import { selectCatalog } from './support'

async function selectHost(page: Page, name: string) {
  // Tall detail cards share the mobile dock with Objects; close through the
  // established Escape interaction before selecting another host.
  if (await page.locator('#planet-card').isVisible()) await page.keyboard.press('Escape')
  const objects = page.getByRole('button', { name: 'Objects', exact: true })
  if (await objects.getAttribute('aria-expanded') === 'false') await objects.click()
  await page.getByLabel('Search objects').fill(name)
  await page.getByRole('button', { name: `Select ${name}`, exact: true }).click()
  if (await objects.getAttribute('aria-expanded') === 'true') await objects.click()
  if (await page.locator('#object-specs-toggle').getAttribute('aria-expanded') === 'false') await page.locator('#object-specs-toggle').click()
}

test('nearby planets open from specs, preserve scientific labels and restore solar controls @mobile', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await selectHost(page, 'Proxima Centauri')
  await expect(page.locator('#selected-swatch')).toHaveAttribute('title', '2 known planets · illustrative orbit')
  await page.locator('#known-planets').focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#object-system')).toBeVisible()
  await expect(page.locator('#object-system .planet-row')).toHaveCount(2)
  await page.locator('.planet-row[data-planet-id="exo-proxima-cen-b"] button').click()
  const card = page.locator('#planet-card')
  await expect(card).toBeVisible()
  await expect(page.locator('#planet-info-toggle')).toBeHidden()
  await expect(page.locator('#planet-moons-toggle')).toBeHidden()
  await expect(page.locator('#planet-globe')).toBeHidden()
  await expect(page.locator('#planet-add-earth')).toBeHidden()
  await expect(page.locator('#planet-atmosphere-section')).toBeHidden()
  await expect(card.locator('[data-planet-spec="mass"]')).toContainText('Minimum mass (m sin i)')
  await expect(card.locator('[data-planet-spec="mass"]')).toContainText('1.06×Earth')
  await expect(card.locator('[data-planet-spec="radius"]')).toContainText('estimated')
  await expect(card.locator('[data-planet-spec="source"] a')).toHaveAttribute('href', /exoplanetarchive.*Proxima/)
  await card.screenshot({ path: testInfo.outputPath('proxima-planet.png') })
  expect(await card.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await selectHost(page, "Barnard's Star")
  await page.locator('#known-planets-row dt').click()
  await expect(page.locator('#object-system .planet-row')).toHaveCount(4)
  await expect(page.locator('#object-system .planet-diagram-label')).toHaveCount(0)
  await page.locator('#selected-object-card').screenshot({ path: testInfo.outputPath('barnard-system.png') })
  await selectHost(page, 'Sirius A')
  await expect(page.locator('#known-planets-row')).toBeHidden()
  await selectHost(page, 'Sun')
  await page.locator('#known-planets').click()
  await expect(page.locator('#object-system .planet-diagram-label')).toHaveCount(0)
  await page.locator('.planet-row[data-planet-id="earth"] button').click()
  await expect(page.locator('#planet-info-toggle')).toBeVisible()
  await expect(page.locator('#planet-atmosphere-section')).toBeVisible()
  await expect(page.locator('#planet-globe')).toHaveAttribute('data-texture-ready', 'true')
  expect(errors).toEqual([])
})

test('extended nearby catalog handles many planets, missing distances and long names @mobile', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await selectCatalog(page, 'nearest-1000')
  await selectHost(page, 'TRAPPIST-1')
  await page.locator('#known-planets').click()
  await expect(page.locator('#object-system .planet-row')).toHaveCount(7)
  await page.locator('.planet-row[data-planet-id="exo-trappist-1-b"] button').click()
  await expect(page.locator('#planet-card [data-planet-spec="radius"]')).not.toContainText('estimated')
  await selectHost(page, 'CD-45 5378')
  await page.locator('#known-planets').click()
  await expect(page.locator('.planet-row[data-planet-id="exo-gj-367-c"] button')).toHaveText('Not available')
  await expect(page.locator('#object-system .planet-body')).toHaveCount(1)
  await page.locator('.planet-row[data-planet-id="exo-gj-367-c"] button').click()
  await expect(page.locator('#planet-card [data-planet-spec="semi-major-axis"]')).toHaveCount(0)
  await selectHost(page, 'WISE J033605.05-014350.4')
  await page.locator('#known-planets').click()
  await page.locator('.planet-row button').click()
  const card = page.locator('#planet-card')
  await expect(card.locator('[data-planet-spec="semi-major-axis"]')).toContainText('Projected separation')
  expect(await card.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  expect(await card.locator('.panel-heading').evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true)
  await card.screenshot({ path: testInfo.outputPath('imaged-planet.png') })
})
