import { expect, test } from '@playwright/test'
import { selectCatalog } from './support'

test('expands Objects horizontally and combines database filters and origin distances @mobile', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  const panel = page.locator('#objects-panel')
  const compact = (await panel.boundingBox())!
  const styles = await page.evaluate(() => {
    const properties = ['height', 'fontSize', 'backgroundColor', 'borderRadius', 'padding'] as const
    const search = getComputedStyle(document.getElementById('object-search')!)
    const saved = getComputedStyle(document.getElementById('save-view-name')!)
    return properties.map((property) => [search[property], saved[property]])
  })
  expect(styles.every(([search, saved]) => search === saved)).toBe(true)
  await page.getByRole('button', { name: 'Expand objects list', exact: true }).click()
  const expanded = (await panel.boundingBox())!
  expect(expanded.width).toBeGreaterThan(compact.width)
  expect(Math.abs(expanded.height - compact.height)).toBeLessThan(1)
  expect(expanded.x).toBeGreaterThanOrEqual(8)
  await expect(panel.locator('.objects-heading #object-search')).toBeVisible()
  await expect(page.locator('#star-list')).toBeHidden()
  await expect(page.locator('.object-column-label')).toHaveText([
    'Name', 'Object type', 'Distance from Sun', 'Sub-type', 'Planets', 'Spectral type',
    'Temperature', 'Bol. luminosity', 'Mass', 'Radius', 'Metallicity', 'Age', 'Abs. mag', 'App. mag',
  ])

  await page.locator('#object-search').fill('Centauri')
  const rows = page.locator('#object-database tbody tr[data-star]')
  await expect(rows).toHaveCount(3)
  await page.locator('button[data-sort="mass"]').click()
  await expect(rows.first()).toHaveAttribute('data-star', 'proxima-centauri')
  await page.locator('button[data-sort="mass"]').click()
  await expect(rows.first()).toHaveAttribute('data-star', 'alpha-centauri-a')
  await expect(page.locator('th[data-column="mass"]')).toHaveAttribute('aria-sort', 'descending')

  await page.getByRole('button', { name: 'Filter spectral type', exact: true }).click()
  const popup = page.locator('#object-column-filter')
  await popup.getByRole('button', { name: 'Clear', exact: true }).click()
  await expect(page.locator('.object-database-empty')).toHaveText('No matching objects')
  await popup.getByRole('checkbox', { name: 'M', exact: true }).check()
  await expect(rows).toHaveCount(1)
  await popup.getByRole('checkbox', { name: 'G', exact: true }).check()
  await expect(rows).toHaveCount(2)
  await popup.getByRole('button', { name: 'All', exact: true }).click()
  await popup.getByRole('checkbox', { name: 'M', exact: true }).press('Escape')
  await expect(page.getByRole('button', { name: 'Filter spectral type', exact: true })).toBeFocused()
  await expect(panel).toBeVisible()

  await page.getByRole('button', { name: 'Filter sub-type', exact: true }).click()
  await popup.getByRole('button', { name: 'Clear', exact: true }).click()
  await popup.getByRole('checkbox', { name: 'Main-sequence', exact: true }).check()
  await popup.getByRole('checkbox', { name: 'BY Draconis variable', exact: true }).check()
  await expect(rows).toHaveCount(3)
  await popup.getByRole('button', { name: 'All', exact: true }).click()
  await popup.getByRole('checkbox', { name: 'Main-sequence', exact: true }).press('Escape')

  await page.getByRole('button', { name: 'Filter object type', exact: true }).click()
  await popup.getByRole('button', { name: 'Clear', exact: true }).click()
  await popup.getByRole('checkbox', { name: 'White dwarf', exact: true }).check()
  await expect(page.locator('.object-database-empty')).toBeVisible()
  await popup.getByRole('checkbox', { name: 'Star', exact: true }).check()
  await expect(rows).toHaveCount(3)
  await popup.getByRole('button', { name: 'All', exact: true }).click()
  await popup.getByRole('checkbox', { name: 'Star', exact: true }).press('Escape')

  await page.getByRole('button', { name: 'Select Proxima Centauri', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Select Proxima Centauri', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.locator('#origin-controls').hover()
  await page.getByRole('button', { name: 'Set selected object as origin', exact: true }).click()
  await page.getByRole('button', { name: 'Switch to distance from Proxima Centauri', exact: true }).click()
  await expect(page.locator('th[data-column="distance"] .object-column-label')).toHaveText('Distance from Proxima Centauri')
  await expect(page.locator('tr[data-star="proxima-centauri"] td[data-column="distance"]')).toHaveText('0.00')
  await page.getByRole('button', { name: 'Switch to distance from Sun', exact: true }).click()
  await expect(page.locator('tr[data-star="proxima-centauri"] td[data-column="distance"]')).toHaveText('4.25')
  await page.screenshot({ path: testInfo.outputPath('objects-database.png') })
  await page.getByRole('button', { name: 'Collapse objects list', exact: true }).click()
  await expect(panel.locator(':scope > .object-search #object-search')).toHaveValue('Centauri')
  await expect(page.locator('#object-database')).toBeHidden()
  await expect(page.locator('#star-list button[data-star]')).toHaveCount(3)
  await expect(page.locator('#star-list button[data-star]').first()).toHaveAttribute('data-star', 'proxima-centauri')
})

test('virtualizes database rows while preserving a sticky header and horizontal alignment', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await selectCatalog(page, 'nearest-1000')
  await expect.poll(async () => Number((await page.locator('#catalog-count').textContent())!.split('/')[1])).toBeGreaterThan(1000)
  await expect(page.locator('#catalog-range-value')).toHaveText(/Nearest 1000/)
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await page.locator('#object-distance-limit').fill('24')
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  await page.getByRole('button', { name: 'Expand objects list', exact: true }).click()
  const database = page.locator('#object-database')
  const rows = database.locator('tbody tr[data-star]')
  expect(await rows.count()).toBeLessThan(40)
  const first = await rows.first().getAttribute('data-star')
  await database.evaluate((node) => { node.scrollTop = 3000; node.scrollLeft = 250 })
  await expect(rows.first()).not.toHaveAttribute('data-star', first!)
  const geometry = await database.evaluate((node) => {
    const bounds = node.getBoundingClientRect()
    const header = node.querySelector('th')!.getBoundingClientRect()
    const name = node.querySelector('tr[data-star] td')!.getBoundingClientRect()
    const rowHeights = [...node.querySelectorAll('tr[data-star]')].map((row) => row.getBoundingClientRect().height)
    return { top: header.top - bounds.top, nameLeft: name.left - bounds.left, headerLeft: header.left - bounds.left, rowHeights }
  })
  expect(Math.abs(geometry.top)).toBeLessThan(1)
  expect(Math.abs(geometry.nameLeft - geometry.headerLeft)).toBeLessThan(1)
  expect(geometry.rowHeights.every((height) => height === 36)).toBe(true)
  await page.locator('#object-search').fill('Sun')
  await expect(database).toHaveJSProperty('scrollTop', 0)
  await expect(database.getByRole('button', { name: 'Select Sun', exact: true })).toBeVisible()
})
