import { expect, test } from '@playwright/test'
import { selectCatalog } from './support'

test('keeps the Mu Cas primary visible when selecting and deselecting B', async ({ page }) => {
  // Expose both component anchors independently of the ordinary label budget.
  await page.addInitScript(() => localStorage.setItem('star-view-label-limit', '140'))
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await page.evaluate(() => document.fonts.ready)
  await selectCatalog(page, 'nearest-1000')
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  await page.getByLabel('Search objects').fill('Mu Cassiopeiae')
  await page.getByRole('button', { name: 'Select Mu Cassiopeiae A', exact: true }).click()
  const primary = page.locator('.map-anchor[data-star-id="cns5-0317"]')
  await expect(primary).toHaveAttribute('data-visibility', 'base')
  await expect(primary).toHaveAttribute('data-halo-visible', 'true')
  await expect(primary).toHaveAttribute('data-core-visible', 'true')
  await page.locator('[data-component-id="mu-cassiopeiae-b"]').click()
  await expect(page.locator('[data-component-id="mu-cassiopeiae-b"]')).toHaveAttribute('aria-pressed', 'true')
  await expect(primary).toHaveAttribute('data-visibility', 'base')
  await expect(primary).toHaveAttribute('data-map-visible', 'true')
  await expect(primary).toHaveAttribute('data-halo-visible', 'true')
  await expect(primary).toHaveAttribute('data-core-visible', 'true')
  const secondary = page.locator('.map-anchor[data-star-id="mu-cassiopeiae-b"]')
  await expect(secondary).toHaveAttribute('data-halo-visible', 'false')
  await expect(secondary).toHaveAttribute('data-core-visible', 'false')
  await expect(secondary.locator('.selection-ring')).toBeHidden()
  await expect(primary).toBeVisible()
  const objects = page.getByRole('button', { name: 'Objects', exact: true })
  if (await objects.getAttribute('aria-expanded') === 'true') await objects.click()
  const filter = page.getByRole('button', { name: 'Filter', exact: true })
  if (await filter.getAttribute('aria-expanded') === 'true') await filter.click()
  await page.locator('#scene canvas').click({ position: { x: 2, y: 2 } })
  await expect(page.locator('.selected-object')).toBeHidden()
  await expect(primary).toHaveAttribute('data-visibility', 'base')
  await expect(primary).toHaveAttribute('data-map-visible', 'true')
  await expect(primary).toHaveAttribute('data-halo-visible', 'true')
  await expect(primary).toHaveAttribute('data-core-visible', 'true')
  await expect(primary).toBeVisible()
})
