import { expect, test, type Page } from '@playwright/test'
import { selectCatalog } from './support'

test('aligns Stein 2051 B with DC and shows family tooltips above the letters', { tag: '@mobile' }, async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await selectCatalog(page, 'nearest-100')
  await expect(page.locator('#scene-status')).toBeHidden()
  await page.getByRole('button', { name: 'Filter', exact: true }).click()
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  await page.getByLabel('Search objects').fill('Stein 2051 B')
  await page.getByRole('button', { name: 'Select Stein 2051 B', exact: true }).click()
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  if (await page.locator('#object-card-details').getAttribute('open') === null) await page.locator('#object-specs-toggle').click()
  await page.locator('#spectral-toggle').click()
  await page.locator('#spectral-mk').click()
  const row = page.locator('.white-dwarf-star.is-selected')
  await row.scrollIntoViewIfNeeded()
  await expect(row).toHaveAttribute('data-family', 'DC')
  await expect(page.locator('.white-dwarf-star-type')).toHaveCount(0)
  const dc = await page.locator('.white-dwarf-family[data-family="DC"]').boundingBox()
  const icon = await row.locator('.white-dwarf-star-icon').boundingBox()
  expect(Math.abs(icon!.x + icon!.width / 2 - dc!.x - dc!.width / 2)).toBeLessThan(1)
  const card = await page.locator('#spectral-card').boundingBox()
  for (const family of ['DA', 'DB', 'DC', 'DO', 'DQ', 'DZ', 'DX']) {
    const button = page.getByRole('button', { name: family, exact: true })
    await button.focus()
    const tooltip = page.locator(`#white-dwarf-${family.toLowerCase()}-tooltip`)
    await expect(tooltip).toBeVisible()
    const letter = await button.boundingBox(), bubble = await tooltip.boundingBox()
    expect(bubble!.y + bubble!.height).toBeLessThan(letter!.y)
    expect(bubble!.x).toBeGreaterThanOrEqual(card!.x)
    expect(bubble!.x + bubble!.width).toBeLessThanOrEqual(card!.x + card!.width)
    const arrow = await tooltip.evaluate((element) => getComputedStyle(element, '::before').content)
    expect(arrow).not.toBe('none')
    await expect(button).not.toHaveAttribute('title')
  }
  await page.getByRole('button', { name: 'DC', exact: true }).focus()
  await page.screenshot({ path: testInfo.outputPath('mk-stein-dc-tooltip.png') })
})

async function expectDistinctMarkerLabels(page: Page, diagram: 'hr' | 'mk') {
  const selected = page.locator(`.${diagram}-selected-marker`)
  const reference = page.locator(`.${diagram}-reference-marker`)
  for (const marker of [selected, reference]) {
    await expect(marker.locator('.spectral-marker-underline')).toHaveCount(1)
    await expect(marker.locator('.spectral-marker-link')).toHaveCount(1)
    const colors = await marker.evaluate((group) => ({
      ring: getComputedStyle(group.querySelector('circle')!).stroke,
      underline: getComputedStyle(group.querySelector('.spectral-marker-underline')!).stroke,
      connector: getComputedStyle(group.querySelector('.spectral-marker-link')!).stroke,
    }))
    expect(colors.underline).toBe(colors.ring)
    expect(colors.connector).toBe(colors.ring)
  }
  const a = await selected.locator('.hr-marker-text').boundingBox()
  const b = await reference.locator('.hr-marker-text').boundingBox()
  expect(a!.x + a!.width <= b!.x || b!.x + b!.width <= a!.x || a!.y + a!.height <= b!.y || b!.y + b!.height <= a!.y).toBe(true)
}

test('plots the selected component, switches magnitude scales, and follows card dismissal behavior', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await expect(page.locator('#scene-status')).toBeHidden()
  await expect(page.locator('#inspector')).toHaveAttribute('data-selected-star', 'sirius-a')
  await page.locator('#object-specs-toggle').click()
  const card = page.locator('#spectral-card')
  const toggle = page.locator('#spectral-toggle')
  await page.locator('.spectral-row dt').click()
  await expect(card).toBeVisible()
  await expect(page.locator('#spectral-heading')).toHaveText('Spectral type')
  await expect(page.locator('#spectral-hr')).toHaveText('H-R')
  await expect(page.locator('#spectral-mk')).toHaveText('M-K')
  await expect(toggle).toHaveAttribute('aria-expanded', 'true')
  await expect(card.locator('svg[role="img"]')).toHaveAccessibleName('Hertzsprung–Russell diagram: Sirius A and Sun')
  await expect(page.locator('#spectral-selected-name')).toHaveText('Sirius A')
  await expect(page.locator('#spectral-reference-magnitude')).toHaveText('4.83')
  await expect(page.locator('.hr-selected-marker')).toHaveCount(1)
  await expect(page.locator('.hr-reference-marker')).toHaveCount(1)
  await expectDistinctMarkerLabels(page, 'hr')
  const selectedBounds = await page.locator('#selected-object-card').boundingBox()
  const cardBounds = await card.boundingBox()
  expect(cardBounds!.x).toBeGreaterThan(selectedBounds!.x + selectedBounds!.width)
  await page.screenshot({ path: testInfo.outputPath('hr-sirius-a.png') })

  await page.locator('#spectral-bolometric').click()
  await expect(page.locator('#spectral-bolometric')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#spectral-reference-magnitude')).toHaveText('4.74')
  await page.keyboard.press('Escape')
  await expect(card).toBeHidden()
  await expect(toggle).toBeFocused()

  const select = async (name: string) => {
    await page.getByRole('button', { name: 'Objects', exact: true }).click()
    await page.getByLabel('Search objects').fill(name)
    await page.getByRole('button', { name: `Select ${name}`, exact: true }).click()
    await page.getByRole('button', { name: 'Objects', exact: true }).click()
    if (await page.locator('#object-card-details').getAttribute('open') === null) await page.locator('#object-specs-toggle').click()
  }
  await page.locator('#star-components [data-component-id="sirius-b"]').click()
  await toggle.click()
  await expect(page.locator('#spectral-selected-name')).toHaveText('Sirius B')
  await expect(page.locator('#spectral-selected-type')).toContainText('DA')
  const whiteDwarf = await page.locator('.hr-selected-marker circle').first().evaluate((circle) => ({ x: Number(circle.getAttribute('cx')), y: Number(circle.getAttribute('cy')) }))
  const sun = await page.locator('.hr-reference-marker circle').evaluate((circle) => ({ x: Number(circle.getAttribute('cx')), y: Number(circle.getAttribute('cy')) }))
  expect(whiteDwarf.x).toBeLessThan(sun.x)
  expect(whiteDwarf.y).toBeGreaterThan(sun.y)
  await page.screenshot({ path: testInfo.outputPath('hr-sirius-b.png') })
  await page.locator('#spectral-mk').click()
  await expect(page.locator('#mk-selected-type')).toHaveText('DA2')
  await expect(page.locator('#mk-selected-class')).toHaveText('Not applicable')
  await expect(page.locator('#mk-missing')).toBeHidden()
  await expect(page.locator('#degenerate-heading')).toHaveText('Degenerate stars')
  await expect(page.locator('.white-dwarf-family-help')).toHaveText(['DA', 'DB', 'DC', 'DO', 'DQ', 'DZ', 'DX'])
  await expect(page.locator('.white-dwarf-family.is-selected .white-dwarf-family-help')).toHaveText('DA')
  await expect(page.locator('.white-dwarf-star.is-selected')).toHaveAttribute('data-family', 'DA')
  await expect(page.locator('.white-dwarf-star-name')).toHaveText('Sirius B')
  await expect(page.locator('.white-dwarf-star-type')).toHaveCount(0)
  await expect(page.locator('.white-dwarf-star img')).toHaveAttribute('src', /^data:image\/png/)
  await page.locator('#white-dwarf-stars').scrollIntoViewIfNeeded()
  await page.screenshot({ path: testInfo.outputPath('mk-sirius-b.png') })
  await page.locator('#spectral-hr').click()

  await select('Luhman 16 A')
  // Selecting through the list may dismiss cards; explicitly open if needed.
  if (await card.isHidden()) await toggle.click()
  await expect(page.locator('#spectral-selected-name')).toHaveText('Luhman 16 A')
  await expect(page.locator('.hr-selected-marker')).toHaveCount(1)
  await page.locator('#spectral-visual').click()
  await expect(page.locator('#spectral-missing')).toContainText('no catalog visual magnitude')
  await expect(page.locator('.hr-selected-marker')).toHaveCount(0)
  await expect(page.locator('.hr-reference-marker')).toHaveCount(1)
  await page.locator('#spectral-bolometric').click()
  await expect(page.locator('#spectral-missing')).toBeHidden()
  await expect(page.locator('.hr-selected-marker')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('hr-luhman-a.png') })
  await page.locator('#radius-toggle').click()
  await expect(card).toBeHidden()
  await expect(page.locator('#radius-card')).toBeVisible()
  await toggle.click()
  await expect(page.locator('#radius-card')).toBeHidden()
  await page.mouse.move(1000, 100)
  await page.mouse.wheel(0, 100)
  await expect(card).toBeHidden()
  await expect(page.locator('#inspector')).toHaveAttribute('data-selected-star', 'luhman-16-a')
  await toggle.click()
  await page.locator('#spectral-close').click()
  await expect(card).toBeHidden()
  await expect(toggle).toBeFocused()

  await select('Sun')
  await toggle.click()
  await expect(page.locator('#spectral-selected-name')).toHaveText('Sun')
  await expect(page.locator('.hr-selected-marker')).toHaveCount(1)
  await expect(page.locator('.hr-reference-marker')).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  const narrowBounds = await card.boundingBox()
  expect(narrowBounds!.x).toBeGreaterThanOrEqual(0)
  expect(narrowBounds!.x + narrowBounds!.width).toBeLessThanOrEqual(390)
  expect(narrowBounds!.y + narrowBounds!.height).toBeLessThanOrEqual(844)
  const diagramBounds = await page.locator('#hr-diagram svg').boundingBox()
  expect(diagramBounds!.x + diagramBounds!.width).toBeLessThanOrEqual(narrowBounds!.x + narrowBounds!.width)
  await page.screenshot({ path: testInfo.outputPath('hr-sun-narrow.png') })
  await page.locator('#spectral-close').click()
  await expect(card).toBeHidden()
})

test('compares with the named origin in H-R and M-K, falling back to Sun for a nebula', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await page.getByRole('button', { name: 'Set selected object as origin', exact: true }).click()
  await expect(page.locator('#reference-base')).toHaveText('Sirius A')
  await page.locator('#object-specs-toggle').click()
  await page.locator('#spectral-toggle').click()
  const card = page.locator('#spectral-card')
  await expect(page.locator('.hr-reference-marker')).toHaveCount(0)
  const select = async (name: string) => {
    const objects = page.getByRole('button', { name: 'Objects', exact: true })
    if (await objects.getAttribute('aria-expanded') === 'false') await objects.click()
    await page.getByLabel('Search objects').fill(name)
    await page.getByRole('button', { name: `Select ${name}`, exact: true }).click()
    if (await objects.getAttribute('aria-expanded') === 'true') await objects.click()
    if (await page.locator('#object-card-details').getAttribute('open') === null) await page.locator('#object-specs-toggle').click()
  }
  await select('Alpha Centauri A')
  if (await card.isHidden()) await page.locator('#spectral-toggle').click()
  await expect(page.locator('#spectral-reference-name')).toHaveText('Sirius A')
  await expect(page.locator('#spectral-reference-type')).toHaveText('A1V')
  await expect(page.locator('.hr-reference-marker title')).toContainText('Sirius A')
  await expect(page.locator('.hr-selected-marker image')).toHaveAttribute('href', /^data:image\/png/)
  await page.screenshot({ path: testInfo.outputPath('hr-alpha-centauri-vs-sirius.png') })
  await page.locator('#spectral-mk').click()
  await expect(page.locator('#spectral-hr-content')).toBeHidden()
  await expect(page.locator('#spectral-mk-content')).toBeVisible()
  await expect(page.locator('#spectral-mk')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('#mk-reference-name')).toHaveText('Sirius A')
  await expect(page.locator('#mk-selected-class')).toHaveText('V')
  await expect(page.locator('#mk-reference-class')).toHaveText('V')
  const selected = page.locator('.mk-selected-marker'), reference = page.locator('.mk-reference-marker')
  expect(Number(await selected.getAttribute('data-x'))).toBeGreaterThan(Number(await reference.getAttribute('data-x')))
  expect(await selected.getAttribute('data-y')).toBe(await reference.getAttribute('data-y'))
  await expectDistinctMarkerLabels(page, 'mk')
  await page.screenshot({ path: testInfo.outputPath('mk-alpha-centauri-vs-sirius.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  const header = await page.locator('#spectral-mk').boundingBox()
  const bounds = await card.boundingBox()
  expect(header!.x + header!.width).toBeLessThan(bounds!.x + bounds!.width)
  await page.screenshot({ path: testInfo.outputPath('mk-narrow.png') })
  await page.setViewportSize({ width: 1440, height: 900 })

  await page.locator('#spectral-close').click()
  await page.getByRole('button', { name: 'Filter', exact: true }).click()
  await page.getByRole('switch', { name: 'Stellar remnants', exact: true }).check()
  await expect(page.locator('#scene-status')).toBeHidden()
  await expect(page.getByRole('switch', { name: 'Stellar remnants', exact: true })).toBeChecked()
  await page.getByLabel('Object visibility distance', { exact: true }).fill('22')
  await expect(page.locator('#object-distance-limit-value')).toHaveText('3000 ly')
  await select('Sh 2-216')
  await page.getByRole('button', { name: 'Set selected object as origin', exact: true }).click()
  await expect(page.locator('#reference-base')).toHaveText('Sh 2-216')
  await select('Sirius A')
  await page.locator('#spectral-toggle').click()
  await expect(page.locator('#mk-reference-name')).toHaveText('Sun')
  await expect(page.locator('#mk-reference-class')).toHaveText('V')
  await page.locator('#spectral-hr').click()
  await expect(page.locator('#spectral-reference-name')).toHaveText('Sun')
  await expect(page.locator('.hr-reference-marker title')).toContainText('Sun')
  await select('Alpha Centauri A')
  if (await card.isHidden()) await page.locator('#spectral-toggle').click()
  await expectDistinctMarkerLabels(page, 'hr')
  await page.screenshot({ path: testInfo.outputPath('hr-close-names.png') })
  await page.locator('#spectral-mk').click()
  await expectDistinctMarkerLabels(page, 'mk')
  await page.screenshot({ path: testInfo.outputPath('mk-close-names.png') })
})
