import { expect, test } from '@playwright/test'
import { openFilter, openSpecs } from './support'

test('selects Dubhe components with separate spectra and companion marks in both object lists', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('#scene')).toHaveAttribute('data-ready', 'true')
  await openFilter(page)
  await page.getByRole('switch', { name: 'Always show bright stars', exact: true }).check()
  await expect(page.locator('#scene-status')).toBeHidden()
  await page.getByLabel('Object visibility distance', { exact: true }).fill('22')
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  await page.getByLabel('Search objects').fill('Dubhe')
  const b = page.getByRole('button', { name: 'Select Dubhe B', exact: true })
  await expect(b.locator('.companion-icon')).toHaveAccessibleName('Dubhe, stellar component B')
  await page.locator('#objects-expand').click()
  await expect(b.locator('.companion-icon')).toHaveCount(1)
  await b.click()
  await page.getByRole('button', { name: 'Objects', exact: true }).click()
  await expect(page.locator('#inspector')).toHaveAttribute('data-selected-star', 'msc-11037+6145-b')
  await expect(page.locator('#star-components .star-component')).toHaveText(['A', 'B', 'Ca', 'Cb', 'D'])
  await expect(page.locator('#star-components [data-component-id="msc-11037+6145-b"]')).toHaveAttribute('aria-pressed', 'true')
  await openSpecs(page)
  await expect(page.locator('#spectral-type')).toHaveText('A7.5')
  await expect(page.locator('#mass')).toHaveText('Not available')
  await page.locator('#spectral-toggle').click()
  await page.locator('#spectral-mk').click()
  await expect(page.locator('#mk-missing')).toContainText('luminosity class is not recorded for A7.5')
  await expect(page.locator('.mk-selected-marker')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('dubhe-b.png') })
  await page.locator('#star-components [data-component-id="bright-dubhe"]').click()
  await expect(page.locator('#spectral-type')).toHaveText('G9III')
  await expect(page.locator('#mass')).toHaveText('4.25 M☉')
  if (await page.locator('#spectral-card').isHidden()) await page.locator('#spectral-toggle').click()
  await expect(page.locator('#mk-selected-class')).toHaveText('III')
  await expect(page.locator('.mk-selected-marker')).toHaveCount(1)
  await page.screenshot({ path: testInfo.outputPath('dubhe-a.png') })
  expect(errors).toEqual([])
})
