import { expect, test, type Page } from '@playwright/test'
import { openViewer, selectCatalog } from './support'

async function selectObject(page: Page, name: string) {
  const objects = page.getByRole('button', { name: 'Objects', exact: true })
  if (await objects.getAttribute('aria-expanded') === 'false') await objects.click()
  await page.getByLabel('Search objects').fill(name)
  await page.getByRole('button', { name: `Select ${name}`, exact: true }).click()
}

test('new system selections reset to A while component controls retain B', { tag: '@mobile' }, async ({ page }) => {
  await openViewer(page)
  await selectObject(page, 'Sirius B')
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('A')
  await page.locator('#star-components [data-component-id="sirius-b"]').click()
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('B')
  await selectObject(page, 'Alpha Centauri B')
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('A')
  await page.locator('#star-components [data-component-id="alpha-centauri-b"]').click()
  await selectObject(page, 'Sirius A')
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('A')
})

test('stellar orbit pairs, barycenters and term tooltips fit the selected card', { tag: '@mobile' }, async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await openViewer(page)
  await selectObject(page, 'Alpha Centauri A')
  await page.locator('#object-system-toggle').click()
  const system = page.locator('#object-system')
  await expect(system).toContainText('3 stars system')
  await expect(system.locator('[data-system-component-id]')).toHaveCount(0)
  const viewToggle = system.getByRole('button', { name: 'Top view of stellar orbit', exact: true })
  const diagram = system.locator('.stellar-orbit-diagram')
  await expect(viewToggle).toHaveAttribute('aria-pressed', 'false')
  await expect(diagram).toHaveAttribute('data-orbit-view', 'sky')
  const skyPath = await diagram.locator('[data-stellar-orbit]').first().getAttribute('d')
  const headerBounds = await system.locator('.stellar-system-heading').boundingBox()
  const toggleBounds = await viewToggle.boundingBox()
  expect(toggleBounds!.x).toBeGreaterThan(headerBounds!.x + headerBounds!.width * 0.75)
  await viewToggle.click()
  await expect(viewToggle).toHaveAttribute('aria-pressed', 'true')
  await expect(diagram).toHaveAttribute('data-orbit-view', 'top')
  expect(await diagram.locator('[data-stellar-orbit]').first().getAttribute('d')).not.toBe(skyPath)
  await expect(system.locator('[data-orbit-spec="inclination"] dd')).toHaveText('79.243°')
  await page.locator('#selected-object-card').screenshot({ path: testInfo.outputPath('stellar-system-top.png') })
  await expect(system.locator('[data-orbit-spec]')).toHaveCount(8)
  await expect(system.locator('[data-barycenter]')).toHaveCount(1)
  await expect(system.locator('[data-orbit-spec="axis"] dd')).toHaveText('23.2988 AU')
  await system.getByRole('button', { name: 'Show AB–C orbit', exact: true }).click()
  await expect(system.locator('[data-orbit-spec="primary"] dd')).toHaveText('AB')
  await expect(system.locator('[data-orbit-spec="period"] dd')).toHaveText('547,000 yr')
  await expect(system.locator('[data-stellar-component]')).toHaveCount(3)
  await expect(diagram).toHaveAttribute('data-orbit-view', 'top')
  await system.getByRole('button', { name: 'Show A–B orbit', exact: true }).click()
  await page.locator('#star-components [data-component-id="alpha-centauri-b"]').click()
  await expect(diagram).toHaveAttribute('data-orbit-view', 'top')
  await system.getByRole('button', { name: 'Top view of stellar orbit', exact: true }).click()
  await expect(diagram).toHaveAttribute('data-orbit-view', 'sky')
  const help = system.getByRole('button', { name: 'Eccentricity', exact: true })
  await help.focus()
  const tooltip = system.locator('#stellar-orbit-eccentricity-tooltip')
  await expect(tooltip).toBeVisible()
  await expect(tooltip).toContainText('0 is circular')
  const bounds = await tooltip.boundingBox()
  const viewport = page.viewportSize()!
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(viewport.width)
  await help.blur()
  expect(await system.evaluate((node) => node.scrollWidth <= node.clientWidth)).toBe(true)
  await page.locator('#selected-object-card').screenshot({ path: testInfo.outputPath('stellar-system.png') })
  expect(errors).toEqual([])
})

test('EZ Aquarii shows its A–C and AC–B orbits with exact component selection', async ({ page }, testInfo) => {
  await openViewer(page)
  await selectObject(page, 'EZ Aquarii A')
  await expect(page.locator('#object-system-toggle')).toBeEnabled()
  await page.locator('#object-system-toggle').click()
  const system = page.locator('#object-system')
  const diagram = system.locator('.stellar-orbit-diagram')
  await expect(system.getByRole('button', { name: 'Show A–C orbit', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(system.locator('[data-orbit-spec="period"] dd')).toHaveText('3.78652 d')
  await expect(system.locator('[data-orbit-spec="eccentricity"] dd')).toHaveText('0')
  await expect(diagram.locator('[data-stellar-orbit]')).toHaveCount(0)
  await expect(system.getByRole('link', { name: 'Sgr2000' })).toHaveAttribute('title', 'ORB6 · incomplete orbital elements')
  await page.locator('#star-components [data-component-id="ez-aquarii-c"]').click()
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('C')
  await expect(system.getByRole('button', { name: 'Show A–C orbit', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await system.getByRole('button', { name: 'Show AC–B orbit', exact: true }).click()
  await expect(system.locator('[data-orbit-spec="primary"] dd')).toHaveText('AC')
  await expect(system.locator('[data-orbit-spec="eccentricity"] dd')).toHaveText('0.439')
  await expect(system.locator('[data-orbit-spec="axis"] dd')).toHaveText('1.1829 AU')
  await expect(diagram.locator('[data-stellar-orbit]')).toHaveCount(2)
  await expect(diagram.locator('[data-stellar-component]')).toHaveCount(3)
  await page.locator('#selected-object-card').screenshot({ path: testInfo.outputPath('ez-aquarii-outer-orbit.png') })
  await page.locator('#star-components [data-component-id="ez-aquarii-b"]').click()
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('B')
  await expect(system.getByRole('button', { name: 'Show AC–B orbit', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('orbit coverage audit restores nearby systems and nested pair controls', async ({ page }, testInfo) => {
  await openViewer(page)
  await selectObject(page, 'Luhman 16 A')
  await expect(page.locator('#object-system-toggle')).toBeEnabled()
  await page.locator('#object-system-toggle').click()
  const system = page.locator('#object-system')
  await expect(system.locator('[data-orbit-spec="period"] dd')).toHaveText('26.55 yr')
  await expect(system.locator('[data-orbit-spec="epoch"] dd')).toHaveText('J2018.06')
  await expect(system.locator('[data-stellar-orbit]')).toHaveCount(2)
  await selectCatalog(page, 'nearest-100')
  await selectObject(page, 'GJ 1245 A')
  await expect(system.getByRole('button', { name: 'Show A–C orbit', exact: true })).toBeVisible()
  await system.getByRole('button', { name: 'Show AC–B orbit', exact: true }).click()
  await expect(system.locator('[data-stellar-component]')).toHaveCount(3)
  await page.locator('#selected-object-card').screenshot({ path: testInfo.outputPath('gj-1245-outer-orbit.png') })
  await selectObject(page, 'eps Ind A')
  await expect(page.locator('#star-components button')).toHaveCount(3)
  await expect(system.getByRole('button', { name: 'Show Ba–Bb orbit', exact: true })).toBeVisible()
  await page.locator('#star-components [data-component-id="10pc-0043"]').click()
  await expect(page.locator('#star-components [aria-pressed="true"]')).toHaveText('Bb')
})

test('empty System tabs are disabled and the Sun planet view remains available', { tag: '@mobile' }, async ({ page }) => {
  await openViewer(page)
  await selectObject(page, 'Ross 154')
  await expect(page.locator('#object-system-toggle')).toBeDisabled()
  await expect(page.locator('#object-system')).not.toContainText('Planet data not added')
  await selectObject(page, 'Sun')
  await expect(page.locator('#object-system-toggle')).toBeEnabled()
  await page.locator('#object-system-toggle').click()
  await expect(page.locator('#object-system .planet-row')).toHaveCount(8)
})
